name: Save PR to Firestore

on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  save-pr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Send PR data to Cloud Function
        id: 'invoke'
        run: |
          ID_TOKEN=$(gcloud auth print-identity-token --audiences=${{ secrets.GCP_FUNCTION_URL }})
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $ID_TOKEN" \
          -d '${{ toJSON(github.event) }}' \
          ${{ secrets.GCP_FUNCTION_URL }}
